name: Release
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Auto Release
        uses: Shiro-nn/release-helper@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
