name: Release
on:
  push:
    branches: [main]
    
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Auto Release
        uses: Shiro-nn/release-helper@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
          OPENAI_API_KEY: ${{ secrets.AI_API_KEY }}
          OPENAI_API_MODEL: deepseek-ai/deepseek-r1
          OPENAI_API_BASE_URL: https://integrate.api.nvidia.com/v1/
